### ISSUE TITLE
Implementing Google Shopping and Dynamic Remarketing for Shop Lavazza

### ISSUE THREAD

**Issue by WLLNick** [SalzmanGroup/spree-google-shopping#18]
We need to implement the code that will allow the Lavazza store to be verified within the Google Merchant Center. Kyle has been provided with it. This directive comes from Lavazza's main headquarters in Italy and it is very important that it be taken care of as soon as possible. This will allow them to utilize dynamic remarketing campaigns and Google shopping campaigns.

**Comment by kylemacey** [comment]
This issue was moved to SalzmanGroup/lavazza#698
